version: "3"

services:
  db:
    container_name: mariadb
    image: mariadb:10-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    #healthcheck:
    #  test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
    #  interval: 3s
    #  retries: 5
    #  start_period: 30s
    #secrets:
    #  - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
    expose:
      - 3306
      - 33060
    ports:
      - "3306:3306"
      - "33060:33060"

  nginx:
    # default ports 80, 443 - expose mapping as needed to host
    image: nginx:1.13-alpine
    container_name: nginx
    env_file:
      - .env
    restart: unless-stopped

    ports:
      - "80:80"    # http
      - "443:443"   # https
    volumes:
      - ../app/portal/static:/var/www/html/static
      - ${NGINX_CONF}:/etc/nginx/conf.d/default.conf
      - ${NGINX_SSL_CERTS}:/etc/ssl:ro
      - ${NGINX_LOGS}:/var/log/nginx

    depends_on:
      - web

  # adminer - bring up only as needed - bypasses nginx
  adminer:
    # default port 8080
    image: adminer:4
    container_name: adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "9000:8080"

  redis:
    container_name: redis
    image: redis:7.2.5-alpine
    restart: always
    ports:
      - "${REDIS_PORT}:6379"

volumes:
  db-data:
      driver: local
#secrets:
#  db-password:
#    file: db/password.txt

