version: '3'
networks:
  nacos:
    driver: bridge
services:
  nacos:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/nacos-server:2.2.0   
    container_name: nacos_server                                 
    restart: unless-stopped                                              
    volumes:                                                     
      - "./nacos/logs:/home/nacos/logs"
    environment:                        
      - PREFER_HOST_MODE=hostname                 
      - MODE=standalone                           
      - SPRING_DATASOURCE_PLATFORM=mysql          
      # TODO modify mysql connection infomation
      - MYSQL_SERVICE_HOST=10.11.68.77          
      - MYSQL_SERVICE_DB_NAME=nacos_config        
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      # TODO modify JVM param
      - JVM_XMS=128m   #-Xms default :2g
      - JVM_XMX=128m   #-Xmx default :2g
      - JVM_XMN=64m    #-Xmn default :1g
      - JVM_MS=32m     #-XX:MetaspaceSize default :128m
      - JVM_MMS=32m    #-XX:MaxMetaspaceSize default :320m
    ports:
      - "8848:8848"
    depends_on:
      - mysql
    networks:
      - nacos
    mem_limit: 1000m   
  mysql:
    image: registry.cn-hangzhou.aliyuncs.com/zhengqing/mysql:5.7
    container_name: nacos-mysql
    restart: unless-stopped
    volumes:
      - "./nacos/mysql5.7/my.cnf:/etc/mysql/my.cnf"
      - "./nacos/mysql5.7/data:/var/lib/mysql"
      - "./nacos/mysql5.7/log/mysql/error.log:/var/log/mysql/error.log"
    environment:
      TZ: Asia/Shanghai
      LANG: en_US.UTF-8
      MYSQL_ROOT_PASSWORD: root        
      MYSQL_DATABASE: nacos_config           
    ports:
      - "3306:3306"
    networks:
      - nacos

